services:
  my-server:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE : postgres

    depends_on:
      my-db:
        condition: service_healthy

  my-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: doc-spring-batch

    volumes:
      - ./postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 10