spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: postgres

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:spring-batch}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  batch:
    jdbc:
      initialize-schema: always
      #table-prefix: SYSTEM_
---
spring:
    config:
      activate:
        on-profile: h2

    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true    # H2 ?? ???

---
spring:
  batch:
    job:
      #name: ${job.name:NONE}
      name: jsonChunkJob
      #enabled: false

---
batch:
  json:
    input: batch-test.json